name: influxdb2
summary: InfluxDB Time Series Database
description: InfluxDB Time Series Database
version: "2.7.12"
adopt-info: overlay

base: core24
grade: devel
confinement: devmode

platforms:
  amd64:

apps:
  influxd:
    command: usr/bin/influxd
    daemon: simple
    plugs: [network, network-bind]

parts:
  influxdb:
    plugin: dump
    source: https://dl.influxdata.com/influxdb/releases/v2.7.12/influxdb2-2.7.12_linux_amd64.tar.gz
  overlay:
    plugin: dump
    source: overlay
    override-stage: |
      craftctl default
      craftctl set version="$(craftctl get version)+git$(git rev-parse --short HEAD)"
